
// This file is generated by setup-monitoring.js
import * as Sentry from '@sentry/nextjs';

Sentry.init({
  dsn: "",
  environment: "production",
  tracesSampleRate: 0.2,
  profilesSampleRate: 0.1,
  replaysSessionSampleRate: 0.1,
  replaysOnErrorSampleRate: 1.0,
  integrations: [
    new Sentry.Integrations.Http({ tracing: true }),
    new Sentry.Integrations.Prisma({ tracing: true }),
  ],
});
