/**
 * Agent Trading System Types
 * 
 * TypeScript definitions that align with the Supabase database schema
 * for the agent trading system.
 */

// Database table types - these will be generated by Supabase gen types
export interface Database {
  public: {
    Tables: {
      agent_trading_permissions: {
        Row: AgentTradingPermissions;
        Insert: AgentTradingPermissionsInsert;
        Update: AgentTradingPermissionsUpdate;
      };
      agent_trades: {
        Row: AgentTrade;
        Insert: AgentTradeInsert;
        Update: AgentTradeUpdate;
      };
      agent_positions: {
        Row: AgentPosition;
        Insert: AgentPositionInsert;
        Update: AgentPositionUpdate;
      };
      agent_performance: {
        Row: AgentPerformance;
        Insert: AgentPerformanceInsert;
        Update: AgentPerformanceUpdate;
      };
      agent_status: {
        Row: AgentStatus;
        Insert: AgentStatusInsert;
        Update: AgentStatusUpdate;
      };
      agent_market_data_subscriptions: {
        Row: AgentMarketDataSubscription;
        Insert: AgentMarketDataSubscriptionInsert;
        Update: AgentMarketDataSubscriptionUpdate;
      };
      agent_state: {
        Row: AgentState;
        Insert: AgentStateInsert;
        Update: AgentStateUpdate;
      };
      agent_checkpoints: {
        Row: AgentCheckpoint;
        Insert: AgentCheckpointInsert;
        Update: AgentCheckpointUpdate;
      };
      agent_decisions: {
        Row: AgentDecision;
        Insert: AgentDecisionInsert;
        Update: AgentDecisionUpdate;
      };
    };
  };
}