-- Create command analytics table
CREATE TABLE IF NOT EXISTS public.command_analytics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  command TEXT NOT NULL,
  duration INTEGER NOT NULL,
  success BOOLEAN NOT NULL,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  agent_id UUID REFERENCES public.elizaos_agents(id),
  error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.command_analytics ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Enable read access for authenticated users" 
ON public.command_analytics
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Enable insert access for service role" 
ON public.command_analytics
FOR INSERT
TO service_role
WITH CHECK (true);
