name: Trading Farm Multi-Chain Integration CI/CD

on:
  push:
    branches: [ main, develop, feat/multi-chain-integration ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      chain:
        description: 'Target chain for manual workflow run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - evm
          - sonic
          - sui
          - solana

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: [evm, sonic, sui, solana]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint
        env:
          TARGET_CHAIN: ${{ matrix.chain }}

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        chain: [evm, sonic, sui, solana]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Install chain-specific dependencies
        run: |
          if [ "${{ matrix.chain }}" == "sui" ]; then
            npm install @mysten/sui.js @m-safe/sui-sdk
          elif [ "${{ matrix.chain }}" == "solana" ]; then
            npm install @solana/web3.js @jup-ag/api @sqds/core
          elif [ "${{ matrix.chain }}" == "sonic" ]; then
            npm install @safe-global/protocol-kit
          fi
      
      - name: Run unit tests
        run: npm test
        env:
          TARGET_CHAIN: ${{ matrix.chain }}

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        chain: [evm, sonic, sui, solana]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Install chain-specific dependencies
        run: |
          if [ "${{ matrix.chain }}" == "sui" ]; then
            npm install @mysten/sui.js @m-safe/sui-sdk
          elif [ "${{ matrix.chain }}" == "solana" ]; then
            npm install @solana/web3.js @jup-ag/api @sqds/core
          elif [ "${{ matrix.chain }}" == "sonic" ]; then
            npm install @safe-global/protocol-kit
          fi
      
      - name: Run integration tests
        run: npm run test:integration
        env:
          TARGET_CHAIN: ${{ matrix.chain }}
          PROVIDER_URL_ETHEREUM: ${{ secrets.PROVIDER_URL_ETHEREUM }}
          PROVIDER_URL_ARBITRUM: ${{ secrets.PROVIDER_URL_ARBITRUM }}
          PROVIDER_URL_POLYGON: ${{ secrets.PROVIDER_URL_POLYGON }}
          PROVIDER_URL_SONIC: ${{ secrets.PROVIDER_URL_SONIC }}
          PROVIDER_URL_SUI: ${{ secrets.PROVIDER_URL_SUI }}
          PROVIDER_URL_SOLANA: ${{ secrets.PROVIDER_URL_SOLANA }}
          TEST_PRIVATE_KEY_EVM: ${{ secrets.TEST_PRIVATE_KEY_EVM }}
          TEST_PRIVATE_KEY_SUI: ${{ secrets.TEST_PRIVATE_KEY_SUI }}
          TEST_PRIVATE_KEY_SOLANA: ${{ secrets.TEST_PRIVATE_KEY_SOLANA }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    strategy:
      matrix:
        chain: [evm, sonic, sui, solana]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Install chain-specific dependencies
        run: |
          if [ "${{ matrix.chain }}" == "sui" ]; then
            npm install @mysten/sui.js @m-safe/sui-sdk
          elif [ "${{ matrix.chain }}" == "solana" ]; then
            npm install @solana/web3.js @jup-ag/api @sqds/core
          elif [ "${{ matrix.chain }}" == "sonic" ]; then
            npm install @safe-global/protocol-kit
          fi
      
      - name: Build
        run: npm run build
        env:
          TARGET_CHAIN: ${{ matrix.chain }}
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-${{ matrix.chain }}
          path: dist/

  docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Generate TypeDoc documentation
        run: npm run docs
      
      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/

  deploy-dev:
    name: Deploy to Development
    if: github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/feat/multi-chain-integration')
    runs-on: ubuntu-latest
    needs: [build, integration-test]
    strategy:
      matrix:
        chain: [evm, sonic, sui, solana]
    steps:
      - uses: actions/checkout@v3
      
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts-${{ matrix.chain }}
          path: dist/
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Deploy to Development Environment
        run: npm run deploy:dev
        env:
          TARGET_CHAIN: ${{ matrix.chain }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

  deploy-prod:
    name: Deploy to Production
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build, integration-test]
    strategy:
      matrix:
        chain: [evm, sonic, sui, solana]
    steps:
      - uses: actions/checkout@v3
      
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts-${{ matrix.chain }}
          path: dist/
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Deploy to Production Environment
        run: npm run deploy:prod
        env:
          TARGET_CHAIN: ${{ matrix.chain }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

  notify:
    name: Notify Team
    if: always()
    runs-on: ubuntu-latest
    needs: [deploy-dev, deploy-prod]
    steps:
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
      
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Build ${{ job.status }}: ${{ github.repository }}"
          body: |
            Build ${{ job.status }}!
            
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
            
            Workflow: ${{ github.workflow }}
            Run URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: ${{ secrets.MAIL_RECIPIENTS }}
          from: GitHub Actions
        if: always() 